import Navbar from "@/components/Navbar/Navbar";
import { PrimeReactProvider } from "primereact/api";
import MobileNav from "@/components/Navbar/MobileNav";
import StarParticles from "@/components/StarParticles";
import "./globals.css";
import { geistMono, geistSans, poppins } from "../../fonts/font";
export const value = {
  appendTo: "self",
};

export const metadata = {
  title: "Portfolio",
  // description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${poppins.className}  ${geistSans.variable} ${geistMono.variable} antialiased `}
        // ${geistSans.variable} ${geistMono.variable}
      >
        <PrimeReactProvider value={value}>
          <Navbar />
          <MobileNav />
          <StarParticles />
          {children}
        </PrimeReactProvider>
      </body>
    </html>
  );
}
